name: Run Acceptance Tests
on:
  push:

permissions:
  contents: read

jobs:
  run-acc-tests:
    runs-on: ubuntu-latest
    env:
      ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
      ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_PUBLIC_KEY }}
      ATLAS_PROJECT_ID: ${{ secrets.ATLAS_PROJECT_ID }}
      ATLAS_ORGANIZATION_ID: ${{ secrets.ATLAS_ORGANIZATION_ID }}

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: .go-version
          cache: true
      - name: Run Acceptance Tests
        run: make testacc
      - name: Run Test Build
        run: make dev
